package com.yuze.user.model;

public class AcPermissionOperation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_permission_operation.id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_permission_operation.permission_id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    private Long permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_permission_operation.operation_id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    private Long operationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_permission_operation.id
     *
     * @return the value of ac_permission_operation.id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_permission_operation.id
     *
     * @param id the value for ac_permission_operation.id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_permission_operation.permission_id
     *
     * @return the value of ac_permission_operation.permission_id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_permission_operation.permission_id
     *
     * @param permissionId the value for ac_permission_operation.permission_id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_permission_operation.operation_id
     *
     * @return the value of ac_permission_operation.operation_id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public Long getOperationId() {
        return operationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_permission_operation.operation_id
     *
     * @param operationId the value for ac_permission_operation.operation_id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public void setOperationId(Long operationId) {
        this.operationId = operationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_operation
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", permissionId=").append(permissionId);
        sb.append(", operationId=").append(operationId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_operation
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AcPermissionOperation other = (AcPermissionOperation) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPermissionId() == null ? other.getPermissionId() == null : this.getPermissionId().equals(other.getPermissionId()))
            && (this.getOperationId() == null ? other.getOperationId() == null : this.getOperationId().equals(other.getOperationId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_operation
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPermissionId() == null) ? 0 : getPermissionId().hashCode());
        result = prime * result + ((getOperationId() == null) ? 0 : getOperationId().hashCode());
        return result;
    }
}