package com.yuze.user.model;

import java.util.Date;

public class AcPermissionMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_permission_menu.id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_permission_menu.permission_id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    private Long permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_permission_menu.menu_id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    private Long menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_permission_menu.gmt_create
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_permission_menu.gmt_modified
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_permission_menu.id
     *
     * @return the value of ac_permission_menu.id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_permission_menu.id
     *
     * @param id the value for ac_permission_menu.id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_permission_menu.permission_id
     *
     * @return the value of ac_permission_menu.permission_id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_permission_menu.permission_id
     *
     * @param permissionId the value for ac_permission_menu.permission_id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_permission_menu.menu_id
     *
     * @return the value of ac_permission_menu.menu_id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_permission_menu.menu_id
     *
     * @param menuId the value for ac_permission_menu.menu_id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_permission_menu.gmt_create
     *
     * @return the value of ac_permission_menu.gmt_create
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_permission_menu.gmt_create
     *
     * @param gmtCreate the value for ac_permission_menu.gmt_create
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_permission_menu.gmt_modified
     *
     * @return the value of ac_permission_menu.gmt_modified
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_permission_menu.gmt_modified
     *
     * @param gmtModified the value for ac_permission_menu.gmt_modified
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_menu
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", permissionId=").append(permissionId);
        sb.append(", menuId=").append(menuId);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_menu
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AcPermissionMenu other = (AcPermissionMenu) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPermissionId() == null ? other.getPermissionId() == null : this.getPermissionId().equals(other.getPermissionId()))
            && (this.getMenuId() == null ? other.getMenuId() == null : this.getMenuId().equals(other.getMenuId()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModified() == null ? other.getGmtModified() == null : this.getGmtModified().equals(other.getGmtModified()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_menu
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPermissionId() == null) ? 0 : getPermissionId().hashCode());
        result = prime * result + ((getMenuId() == null) ? 0 : getMenuId().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        return result;
    }
}