package com.yuze.user.model;

import java.io.Serializable;
import java.util.Date;

public class AcPermission implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_permission.id
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_permission.gmt_create
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_permission.gmt_modified
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_permission.type
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_permission.name
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_permission.uri
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private String uri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_permission.uri_prefix
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private String uriPrefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_permission.code
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_permission.parent_id
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private Long parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_permission.id
     *
     * @return the value of ac_permission.id
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_permission.id
     *
     * @param id the value for ac_permission.id
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_permission.gmt_create
     *
     * @return the value of ac_permission.gmt_create
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_permission.gmt_create
     *
     * @param gmtCreate the value for ac_permission.gmt_create
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_permission.gmt_modified
     *
     * @return the value of ac_permission.gmt_modified
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_permission.gmt_modified
     *
     * @param gmtModified the value for ac_permission.gmt_modified
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_permission.type
     *
     * @return the value of ac_permission.type
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_permission.type
     *
     * @param type the value for ac_permission.type
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_permission.name
     *
     * @return the value of ac_permission.name
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_permission.name
     *
     * @param name the value for ac_permission.name
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_permission.uri
     *
     * @return the value of ac_permission.uri
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_permission.uri
     *
     * @param uri the value for ac_permission.uri
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setUri(String uri) {
        this.uri = uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_permission.uri_prefix
     *
     * @return the value of ac_permission.uri_prefix
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public String getUriPrefix() {
        return uriPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_permission.uri_prefix
     *
     * @param uriPrefix the value for ac_permission.uri_prefix
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setUriPrefix(String uriPrefix) {
        this.uriPrefix = uriPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_permission.code
     *
     * @return the value of ac_permission.code
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_permission.code
     *
     * @param code the value for ac_permission.code
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_permission.parent_id
     *
     * @return the value of ac_permission.parent_id
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_permission.parent_id
     *
     * @param parentId the value for ac_permission.parent_id
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", type=").append(type);
        sb.append(", name=").append(name);
        sb.append(", uri=").append(uri);
        sb.append(", uriPrefix=").append(uriPrefix);
        sb.append(", code=").append(code);
        sb.append(", parentId=").append(parentId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AcPermission other = (AcPermission) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModified() == null ? other.getGmtModified() == null : this.getGmtModified().equals(other.getGmtModified()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getUri() == null ? other.getUri() == null : this.getUri().equals(other.getUri()))
            && (this.getUriPrefix() == null ? other.getUriPrefix() == null : this.getUriPrefix().equals(other.getUriPrefix()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getParentId() == null ? other.getParentId() == null : this.getParentId().equals(other.getParentId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getUri() == null) ? 0 : getUri().hashCode());
        result = prime * result + ((getUriPrefix() == null) ? 0 : getUriPrefix().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
        return result;
    }
}