package com.yuze.user.model;

import java.util.Date;

public class AcUserAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_auth.id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_auth.gmt_create
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_auth.gmt_modified
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_auth.identify_type
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    private String identifyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_auth.credential
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    private String credential;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_auth.is_verified
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    private Byte isVerified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_auth.log_ip
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    private String logIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_auth.user_id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_auth.identifier
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    private String identifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_auth.open_id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_auth.access_token
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    private String accessToken;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_auth.id
     *
     * @return the value of ac_user_auth.id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_auth.id
     *
     * @param id the value for ac_user_auth.id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_auth.gmt_create
     *
     * @return the value of ac_user_auth.gmt_create
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_auth.gmt_create
     *
     * @param gmtCreate the value for ac_user_auth.gmt_create
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_auth.gmt_modified
     *
     * @return the value of ac_user_auth.gmt_modified
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_auth.gmt_modified
     *
     * @param gmtModified the value for ac_user_auth.gmt_modified
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_auth.identify_type
     *
     * @return the value of ac_user_auth.identify_type
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public String getIdentifyType() {
        return identifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_auth.identify_type
     *
     * @param identifyType the value for ac_user_auth.identify_type
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public void setIdentifyType(String identifyType) {
        this.identifyType = identifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_auth.credential
     *
     * @return the value of ac_user_auth.credential
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public String getCredential() {
        return credential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_auth.credential
     *
     * @param credential the value for ac_user_auth.credential
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public void setCredential(String credential) {
        this.credential = credential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_auth.is_verified
     *
     * @return the value of ac_user_auth.is_verified
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public Byte getIsVerified() {
        return isVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_auth.is_verified
     *
     * @param isVerified the value for ac_user_auth.is_verified
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public void setIsVerified(Byte isVerified) {
        this.isVerified = isVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_auth.log_ip
     *
     * @return the value of ac_user_auth.log_ip
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public String getLogIp() {
        return logIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_auth.log_ip
     *
     * @param logIp the value for ac_user_auth.log_ip
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public void setLogIp(String logIp) {
        this.logIp = logIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_auth.user_id
     *
     * @return the value of ac_user_auth.user_id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_auth.user_id
     *
     * @param userId the value for ac_user_auth.user_id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_auth.identifier
     *
     * @return the value of ac_user_auth.identifier
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_auth.identifier
     *
     * @param identifier the value for ac_user_auth.identifier
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_auth.open_id
     *
     * @return the value of ac_user_auth.open_id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_auth.open_id
     *
     * @param openId the value for ac_user_auth.open_id
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_auth.access_token
     *
     * @return the value of ac_user_auth.access_token
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_auth.access_token
     *
     * @param accessToken the value for ac_user_auth.access_token
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_auth
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", identifyType=").append(identifyType);
        sb.append(", credential=").append(credential);
        sb.append(", isVerified=").append(isVerified);
        sb.append(", logIp=").append(logIp);
        sb.append(", userId=").append(userId);
        sb.append(", identifier=").append(identifier);
        sb.append(", openId=").append(openId);
        sb.append(", accessToken=").append(accessToken);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_auth
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AcUserAuth other = (AcUserAuth) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModified() == null ? other.getGmtModified() == null : this.getGmtModified().equals(other.getGmtModified()))
            && (this.getIdentifyType() == null ? other.getIdentifyType() == null : this.getIdentifyType().equals(other.getIdentifyType()))
            && (this.getCredential() == null ? other.getCredential() == null : this.getCredential().equals(other.getCredential()))
            && (this.getIsVerified() == null ? other.getIsVerified() == null : this.getIsVerified().equals(other.getIsVerified()))
            && (this.getLogIp() == null ? other.getLogIp() == null : this.getLogIp().equals(other.getLogIp()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getIdentifier() == null ? other.getIdentifier() == null : this.getIdentifier().equals(other.getIdentifier()))
            && (this.getOpenId() == null ? other.getOpenId() == null : this.getOpenId().equals(other.getOpenId()))
            && (this.getAccessToken() == null ? other.getAccessToken() == null : this.getAccessToken().equals(other.getAccessToken()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_auth
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        result = prime * result + ((getIdentifyType() == null) ? 0 : getIdentifyType().hashCode());
        result = prime * result + ((getCredential() == null) ? 0 : getCredential().hashCode());
        result = prime * result + ((getIsVerified() == null) ? 0 : getIsVerified().hashCode());
        result = prime * result + ((getLogIp() == null) ? 0 : getLogIp().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getIdentifier() == null) ? 0 : getIdentifier().hashCode());
        result = prime * result + ((getOpenId() == null) ? 0 : getOpenId().hashCode());
        result = prime * result + ((getAccessToken() == null) ? 0 : getAccessToken().hashCode());
        return result;
    }
}