package com.yuze.user.model;

import java.util.Date;

public class AcUserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_info.id
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_info.user_id
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_info.gmt_create
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_info.gmt_modified
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_info.bday
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private Date bday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_info.email
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_info.phone
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_info.QQ
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_info.wechat
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private String wechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_info.nickname
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_info.avatar
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_info.age
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private Byte age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_info.gender
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_info.location
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_info.profession
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private String profession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_info.hometown
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private String hometown;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_info.postcode
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    private String postcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_info.id
     *
     * @return the value of ac_user_info.id
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_info.id
     *
     * @param id the value for ac_user_info.id
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_info.user_id
     *
     * @return the value of ac_user_info.user_id
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_info.user_id
     *
     * @param userId the value for ac_user_info.user_id
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_info.gmt_create
     *
     * @return the value of ac_user_info.gmt_create
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_info.gmt_create
     *
     * @param gmtCreate the value for ac_user_info.gmt_create
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_info.gmt_modified
     *
     * @return the value of ac_user_info.gmt_modified
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_info.gmt_modified
     *
     * @param gmtModified the value for ac_user_info.gmt_modified
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_info.bday
     *
     * @return the value of ac_user_info.bday
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public Date getBday() {
        return bday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_info.bday
     *
     * @param bday the value for ac_user_info.bday
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setBday(Date bday) {
        this.bday = bday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_info.email
     *
     * @return the value of ac_user_info.email
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_info.email
     *
     * @param email the value for ac_user_info.email
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_info.phone
     *
     * @return the value of ac_user_info.phone
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_info.phone
     *
     * @param phone the value for ac_user_info.phone
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_info.QQ
     *
     * @return the value of ac_user_info.QQ
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_info.QQ
     *
     * @param qq the value for ac_user_info.QQ
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_info.wechat
     *
     * @return the value of ac_user_info.wechat
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_info.wechat
     *
     * @param wechat the value for ac_user_info.wechat
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_info.nickname
     *
     * @return the value of ac_user_info.nickname
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_info.nickname
     *
     * @param nickname the value for ac_user_info.nickname
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_info.avatar
     *
     * @return the value of ac_user_info.avatar
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_info.avatar
     *
     * @param avatar the value for ac_user_info.avatar
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_info.age
     *
     * @return the value of ac_user_info.age
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public Byte getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_info.age
     *
     * @param age the value for ac_user_info.age
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setAge(Byte age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_info.gender
     *
     * @return the value of ac_user_info.gender
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_info.gender
     *
     * @param gender the value for ac_user_info.gender
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_info.location
     *
     * @return the value of ac_user_info.location
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_info.location
     *
     * @param location the value for ac_user_info.location
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_info.profession
     *
     * @return the value of ac_user_info.profession
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_info.profession
     *
     * @param profession the value for ac_user_info.profession
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setProfession(String profession) {
        this.profession = profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_info.hometown
     *
     * @return the value of ac_user_info.hometown
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public String getHometown() {
        return hometown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_info.hometown
     *
     * @param hometown the value for ac_user_info.hometown
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setHometown(String hometown) {
        this.hometown = hometown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_info.postcode
     *
     * @return the value of ac_user_info.postcode
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_info.postcode
     *
     * @param postcode the value for ac_user_info.postcode
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_info
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", bday=").append(bday);
        sb.append(", email=").append(email);
        sb.append(", phone=").append(phone);
        sb.append(", qq=").append(qq);
        sb.append(", wechat=").append(wechat);
        sb.append(", nickname=").append(nickname);
        sb.append(", avatar=").append(avatar);
        sb.append(", age=").append(age);
        sb.append(", gender=").append(gender);
        sb.append(", location=").append(location);
        sb.append(", profession=").append(profession);
        sb.append(", hometown=").append(hometown);
        sb.append(", postcode=").append(postcode);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_info
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AcUserInfo other = (AcUserInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModified() == null ? other.getGmtModified() == null : this.getGmtModified().equals(other.getGmtModified()))
            && (this.getBday() == null ? other.getBday() == null : this.getBday().equals(other.getBday()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getQq() == null ? other.getQq() == null : this.getQq().equals(other.getQq()))
            && (this.getWechat() == null ? other.getWechat() == null : this.getWechat().equals(other.getWechat()))
            && (this.getNickname() == null ? other.getNickname() == null : this.getNickname().equals(other.getNickname()))
            && (this.getAvatar() == null ? other.getAvatar() == null : this.getAvatar().equals(other.getAvatar()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getGender() == null ? other.getGender() == null : this.getGender().equals(other.getGender()))
            && (this.getLocation() == null ? other.getLocation() == null : this.getLocation().equals(other.getLocation()))
            && (this.getProfession() == null ? other.getProfession() == null : this.getProfession().equals(other.getProfession()))
            && (this.getHometown() == null ? other.getHometown() == null : this.getHometown().equals(other.getHometown()))
            && (this.getPostcode() == null ? other.getPostcode() == null : this.getPostcode().equals(other.getPostcode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_info
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        result = prime * result + ((getBday() == null) ? 0 : getBday().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getQq() == null) ? 0 : getQq().hashCode());
        result = prime * result + ((getWechat() == null) ? 0 : getWechat().hashCode());
        result = prime * result + ((getNickname() == null) ? 0 : getNickname().hashCode());
        result = prime * result + ((getAvatar() == null) ? 0 : getAvatar().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getGender() == null) ? 0 : getGender().hashCode());
        result = prime * result + ((getLocation() == null) ? 0 : getLocation().hashCode());
        result = prime * result + ((getProfession() == null) ? 0 : getProfession().hashCode());
        result = prime * result + ((getHometown() == null) ? 0 : getHometown().hashCode());
        result = prime * result + ((getPostcode() == null) ? 0 : getPostcode().hashCode());
        return result;
    }
}