package com.yuze.user.dao;

import com.yuze.user.model.AcElement;
import com.yuze.user.model.AcElementExample;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface AcElementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_element
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    long countByExample(AcElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_element
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int deleteByExample(AcElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_element
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_element
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int insert(AcElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_element
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int insertSelective(AcElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_element
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    List<AcElement> selectByExample(AcElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_element
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    AcElement selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_element
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") AcElement record, @Param("example") AcElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_element
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int updateByExample(@Param("record") AcElement record, @Param("example") AcElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_element
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int updateByPrimaryKeySelective(AcElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_element
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int updateByPrimaryKey(AcElement record);
}