package com.yuze.user.dao;

import com.yuze.user.model.AcOperation;
import com.yuze.user.model.AcOperationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcOperationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_operation
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    long countByExample(AcOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_operation
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int deleteByExample(AcOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_operation
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_operation
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int insert(AcOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_operation
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int insertSelective(AcOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_operation
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    List<AcOperation> selectByExample(AcOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_operation
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    AcOperation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_operation
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") AcOperation record, @Param("example") AcOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_operation
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByExample(@Param("record") AcOperation record, @Param("example") AcOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_operation
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByPrimaryKeySelective(AcOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_operation
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByPrimaryKey(AcOperation record);
}