package com.yuze.user.dao;

import com.yuze.user.model.AcPermissionMenu;
import com.yuze.user.model.AcPermissionMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcPermissionMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_menu
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    long countByExample(AcPermissionMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_menu
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int deleteByExample(AcPermissionMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_menu
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_menu
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int insert(AcPermissionMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_menu
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int insertSelective(AcPermissionMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_menu
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    List<AcPermissionMenu> selectByExample(AcPermissionMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_menu
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    AcPermissionMenu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_menu
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") AcPermissionMenu record, @Param("example") AcPermissionMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_menu
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByExample(@Param("record") AcPermissionMenu record, @Param("example") AcPermissionMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_menu
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByPrimaryKeySelective(AcPermissionMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_menu
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByPrimaryKey(AcPermissionMenu record);
}