package com.yuze.user.dao;

import com.yuze.user.model.AcPermissionOperation;
import com.yuze.user.model.AcPermissionOperationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcPermissionOperationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_operation
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    long countByExample(AcPermissionOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_operation
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int deleteByExample(AcPermissionOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_operation
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_operation
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int insert(AcPermissionOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_operation
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int insertSelective(AcPermissionOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_operation
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    List<AcPermissionOperation> selectByExample(AcPermissionOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_operation
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    AcPermissionOperation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_operation
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") AcPermissionOperation record, @Param("example") AcPermissionOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_operation
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int updateByExample(@Param("record") AcPermissionOperation record, @Param("example") AcPermissionOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_operation
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int updateByPrimaryKeySelective(AcPermissionOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_operation
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int updateByPrimaryKey(AcPermissionOperation record);
}