package com.yuze.user.dao;

import com.yuze.user.model.AcPermission;
import com.yuze.user.model.AcPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    long countByExample(AcPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int deleteByExample(AcPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int insert(AcPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int insertSelective(AcPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    List<AcPermission> selectByExample(AcPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    AcPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") AcPermission record, @Param("example") AcPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int updateByExample(@Param("record") AcPermission record, @Param("example") AcPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int updateByPrimaryKeySelective(AcPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int updateByPrimaryKey(AcPermission record);
}