package com.yuze.user.dao;

import com.yuze.user.model.AcPermissionElement;
import com.yuze.user.model.AcPermissionElementExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcPermissionElementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_element
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    long countByExample(AcPermissionElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_element
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int deleteByExample(AcPermissionElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_element
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_element
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int insert(AcPermissionElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_element
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int insertSelective(AcPermissionElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_element
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    List<AcPermissionElement> selectByExample(AcPermissionElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_element
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    AcPermissionElement selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_element
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") AcPermissionElement record, @Param("example") AcPermissionElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_element
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByExample(@Param("record") AcPermissionElement record, @Param("example") AcPermissionElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_element
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByPrimaryKeySelective(AcPermissionElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_permission_element
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByPrimaryKey(AcPermissionElement record);
}