package com.yuze.user.dao;

import com.yuze.user.model.AcRoleGroupRole;
import com.yuze.user.model.AcRoleGroupRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcRoleGroupRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_group_role
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    long countByExample(AcRoleGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_group_role
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int deleteByExample(AcRoleGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_group_role
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_group_role
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int insert(AcRoleGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_group_role
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int insertSelective(AcRoleGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_group_role
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    List<AcRoleGroupRole> selectByExample(AcRoleGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_group_role
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    AcRoleGroupRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_group_role
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int updateByExampleSelective(@Param("record") AcRoleGroupRole record, @Param("example") AcRoleGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_group_role
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int updateByExample(@Param("record") AcRoleGroupRole record, @Param("example") AcRoleGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_group_role
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int updateByPrimaryKeySelective(AcRoleGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_group_role
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int updateByPrimaryKey(AcRoleGroupRole record);
}