package com.yuze.user.dao;

import com.yuze.user.model.AcRolePermission;
import com.yuze.user.model.AcRolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    long countByExample(AcRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int deleteByExample(AcRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int insert(AcRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int insertSelective(AcRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    List<AcRolePermission> selectByExample(AcRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    AcRolePermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") AcRolePermission record, @Param("example") AcRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int updateByExample(@Param("record") AcRolePermission record, @Param("example") AcRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int updateByPrimaryKeySelective(AcRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_permission
     *
     * @mbg.generated Tue Jul 04 11:09:44 CST 2017
     */
    int updateByPrimaryKey(AcRolePermission record);
}