package com.yuze.user.dao;

import com.yuze.user.model.AcRole;
import com.yuze.user.model.AcRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    long countByExample(AcRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int deleteByExample(AcRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int insert(AcRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int insertSelective(AcRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    List<AcRole> selectByExample(AcRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    AcRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") AcRole record, @Param("example") AcRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByExample(@Param("record") AcRole record, @Param("example") AcRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByPrimaryKeySelective(AcRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByPrimaryKey(AcRole record);
}