package com.yuze.user.dao;

import com.yuze.user.model.AcUserGroupUser;
import com.yuze.user.model.AcUserGroupUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcUserGroupUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group_user
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    long countByExample(AcUserGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group_user
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int deleteByExample(AcUserGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group_user
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group_user
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int insert(AcUserGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group_user
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int insertSelective(AcUserGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group_user
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    List<AcUserGroupUser> selectByExample(AcUserGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group_user
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    AcUserGroupUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group_user
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") AcUserGroupUser record, @Param("example") AcUserGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group_user
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByExample(@Param("record") AcUserGroupUser record, @Param("example") AcUserGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group_user
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByPrimaryKeySelective(AcUserGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group_user
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByPrimaryKey(AcUserGroupUser record);
}