package com.yuze.user.dao;

import com.yuze.user.model.AcUserRole;
import com.yuze.user.model.AcUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    long countByExample(AcUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int deleteByExample(AcUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int insert(AcUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int insertSelective(AcUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    List<AcUserRole> selectByExample(AcUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    AcUserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") AcUserRole record, @Param("example") AcUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByExample(@Param("record") AcUserRole record, @Param("example") AcUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByPrimaryKeySelective(AcUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbg.generated Thu Jul 06 15:16:58 CST 2017
     */
    int updateByPrimaryKey(AcUserRole record);
}