package com.yuze.user.dao;

import com.yuze.user.model.AcUserAuth;
import com.yuze.user.model.AcUserAuthExample;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AcUserAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_auth
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    long countByExample(AcUserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_auth
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int deleteByExample(AcUserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_auth
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_auth
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int insert(AcUserAuth record);

    int batchInsert(List<AcUserAuth> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_auth
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int insertSelective(AcUserAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_auth
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    List<AcUserAuth> selectByExample(AcUserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_auth
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    AcUserAuth selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_auth
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int updateByExampleSelective(@Param("record") AcUserAuth record, @Param("example") AcUserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_auth
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int updateByExample(@Param("record") AcUserAuth record, @Param("example") AcUserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_auth
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int updateByPrimaryKeySelective(AcUserAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_auth
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int updateByPrimaryKey(AcUserAuth record);

    /**
     * 用户登录验证查询
     */
    AcUserAuth authentication(@Param("record") AcUserAuth record);
}