package com.yuze.user.dao;

import com.github.pagehelper.Page;
import com.yuze.framework.dao.BaseDao;
import com.yuze.user.model.AcUser;
import com.yuze.user.model.AcUserAuth;
import com.yuze.user.model.AcUserExample;
import com.yuze.user.model.AcUserSpec;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AcUserMapper extends BaseDao<AcUserAuth, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    long countByExample(AcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int deleteByExample(AcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int insert(AcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int insertSelective(AcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    List<AcUser> selectByExample(AcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    AcUserAuth selectByPrimaryKey(Long id);

    AcUserSpec selectSpecByPrimaryKey(Long id);

    AcUserSpec selectSpecByUsername(String username);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int updateByExampleSelective(@Param("record") AcUser record, @Param("example") AcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int updateByExample(@Param("record") AcUser record, @Param("example") AcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int updateByPrimaryKeySelective(AcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int updateByPrimaryKey(AcUser record);


    /**
     * 分页条件查询
     */
    List<AcUserSpec> selectByExampleAndPage(Page<AcUser> page, AcUserAuth example);
}