package com.yuze.user.dao;

import com.yuze.user.model.AcUserGroup;
import com.yuze.user.model.AcUserGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcUserGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    long countByExample(AcUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int deleteByExample(AcUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int insert(AcUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int insertSelective(AcUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    List<AcUserGroup> selectByExample(AcUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    AcUserGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int updateByExampleSelective(@Param("record") AcUserGroup record, @Param("example") AcUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int updateByExample(@Param("record") AcUserGroup record, @Param("example") AcUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int updateByPrimaryKeySelective(AcUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_group
     *
     * @mbg.generated Fri Jul 07 08:50:10 CST 2017
     */
    int updateByPrimaryKey(AcUserGroup record);
}